apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver-deployment
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: frknuzn/eurekaserver:latest
        ports:
        - containerPort: 8070
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom: 
            configMapKeyRef:
              name: frknuzn-configmap
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom: 
            configMapKeyRef:
              name: frknuzn-configmap
              key: SPRING_ZIPKIN_BASEURL
        - name: SPRING_CONFIG_IMPORT
          valueFrom: 
            configMapKeyRef:
              name: frknuzn-configmap
              key: SPRING_CONFIG_IMPORT

---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver-service
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
